from tkinter import *
root = Tk()
root.geometry("300x530")
root.title("Calculator by Rajkumar")
scvalue = StringVar()
scvalue.set("")
screen = Entry(root, textvar=scvalue, font="lucida 20 bold")
screen.pack(fill=X, ipadx=8, pady=18, padx=10)
def click(event):
    current_text = scvalue.get()
    button_text = event.widget.cget("text")
    scvalue.set(current_text + button_text)
def evaluate():
    try:
        result = eval(scvalue.get())
        scvalue.set(result)
    except Exception as e:
        scvalue.set("Error")
def clear():
    scvalue.set("")
f = Frame(root, bg="grey")
b = Button(f, text="9", padx=5, pady=5, font="lucida 20 bold")
b.pack(side=LEFT, padx=5, pady=5)
b.bind("<Button-1>", lambda e: click(e))
b = Button(f, text="8", padx=5, pady=5, font="lucida 20 bold")
b.pack(side=LEFT, padx=5, pady=5)
b.bind("<Button-1>", lambda e: click(e))
b = Button(f, text="7", padx=5, pady=5, font="lucida 20 bold")
b.pack(side=LEFT, padx=5, pady=5)
b.bind("<Button-1>", lambda e: click(e))
f.pack()
f = Frame(root, bg="grey")
b = Button(f, text="6", padx=5, pady=5, font="lucida 20 bold")
b.pack(side=LEFT, padx=5, pady=5)
b.bind("<Button-1>", lambda e: click(e))
b = Button(f, text="5", padx=5, pady=5, font="lucida 20 bold")
b.pack(side=LEFT, padx=5, pady=5)
b.bind("<Button-1>", lambda e: click(e))
b = Button(f, text="4", padx=5, pady=5, font="lucida 20 bold")
b.pack(side=LEFT, padx=5, pady=5)
b.bind("<Button-1>", lambda e: click(e))
f.pack()
f = Frame(root, bg="grey")
b = Button(f, text="3", padx=5, pady=5, font="lucida 20 bold")
b.pack(side=LEFT, padx=5, pady=5)
b.bind("<Button-1>", lambda e: click(e))
b = Button(f, text="2", padx=5, pady=5, font="lucida 20 bold")
b.pack(side=LEFT, padx=5, pady=5)
b.bind("<Button-1>", lambda e: click(e))
b = Button(f, text="1", padx=5, pady=5, font="lucida 20 bold")
b.pack(side=LEFT, padx=5, pady=5)
b.bind("<Button-1>", lambda e: click(e))
f.pack()
f = Frame(root, bg="grey")
b = Button(f, text="0", padx=6, pady=6, font="lucida 20 bold")
b.pack(side=LEFT, padx=6, pady=6)
b.bind("<Button-1>", lambda e: click(e))
b = Button(f, text="-", padx=6, pady=6, font="lucida 20 bold")
b.pack(side=LEFT, padx=6, pady=6)
b.bind("<Button-1>", lambda e: click(e))
b = Button(f, text="*", padx=6, pady=6, font="lucida 20 bold")
b.pack(side=LEFT, padx=6, pady=6)
b.bind("<Button-1>", lambda e: click(e))
f.pack()
f = Frame(root, bg="grey")
b = Button(f, text="/", padx=5, pady=5, font="lucida 20 bold")
b.pack(side=LEFT, padx=5, pady=5)
b.bind("<Button-1>", lambda e: click(e))
b = Button(f, text="%", padx=5, pady=5, font="lucida 20 bold")
b.pack(side=LEFT, padx=5, pady=5)
b.bind("<Button-1>", lambda e: click(e))
b = Button(f, text="=", padx=5, pady=5, font="lucida 20 bold")
b.pack(side=LEFT, padx=5, pady=5)
b.bind("<Button-1>", lambda e: evaluate())
f.pack()
f = Frame(root, bg="grey")
b = Button(f, text="C", padx=4, pady=4, font="lucida 20 bold")
b.pack(side=LEFT, padx=4, pady=4)
b.bind("<Button-1>", lambda e: clear())
b = Button(f, text=".", padx=4, pady=4, font="lucida 20 bold")
b.pack(side=LEFT, padx=4, pady=4)
b.bind("<Button-1>", lambda e: click(e))
b = Button(f, text="00", padx=4, pady=4, font="lucida 20 bold")
b.pack(side=LEFT, padx=4, pady=4)
b.bind("<Button-1>", lambda e: click(e))
f.pack()
root.mainloop()


